### ISSUE TITLE
Update README tracking issue

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#14]
- [x] List guiding principles for this template (e.g. no 3rd-party non-bevy dependencies)
- [x] Update Github CI / CD instructions
- [x] Mention some "must-have" 3rd-party bevy dependencies like inspector, LWIM, physics, etc.
- [x] Mention the `rust-analyzer` target dir tradeoff
- [x] Mention copying `.cargo/config_fast_builds.toml` to `.cargo/config.toml`
- [x] Link to the Bevy quick-start guide? (https://bevyengine.org/learn/quick-start/introduction/)
- [x] Link to some alternative 3rd-party bevy templates
- [x] Link to https://the-bevy-flock.itch.io/bevy-template
- [x] Explain `src/` project structure
- [x] Update licensing info (e.g. bevy logo) https://github.com/TheBevyFlock/bevy-template/issues/72

**Comment by janhohenheim** [comment]
Copy-pasting some stuff from Discord:
- no 3rd-party dependencies outside of bevy
- CI with auto-publish to itch.io
- some basic game code written out already (states, system sets, menu, credits)
- extra tooling / conveniences like IDE support, cargo-generate, etc.
- boilerplate workarounds for common bevy issues like screen flickering etc.

**Comment by benfrankel** [comment]
Also, https://github.com/TheBevyFlock/bevy-template/issues/4 is relevant. What is considered "good style" or "idiomatic" will change as new bevy versions are released, so keeping things idiomatic could be a guiding principle as well.

**Comment by MiniaczQ** [comment]
https://github.com/TheBevyFlock/bevy-template/issues/33#issuecomment-2211261540

**Comment by benfrankel** [comment]
https://github.com/TheBevyFlock/bevy-template/issues/25

**Comment by janhohenheim** [comment]
https://github.com/TheBevyFlock/bevy-template/issues/53

**Comment by benfrankel** [comment]
This'll probably be a merge conflict mess, or one person doing all the work, if we do this via PRs. Probably better to work on this as a shared hackmd before making any PRs.

**Comment by benfrankel** [comment]
Moving to `Bevy Jam 6` milestone for the remaining tasks.

**Comment by janhohenheim** [comment]
Nah I'm getting this in for this jam 💪
